apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasknode
  template:
    metadata:
      labels:
        app: flasknode
    spec:
      containers:
      - name: flasknode
        image: icr.io/finalns/finalrepo
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        nodePort: 32000